project:
  type: website

website:
  title: "EPID8313 (year 2025) Lab Review"
  search: true
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Lab2.qmd
        text: Lab2
      - href: Assignment1.qmd
        text: Assignment1
      - href: Lab3.qmd
        text: Lab3
      - href: Lab4.qmd
        text: Lab4
      - href: Assignment2.qmd
        text: Assignment2
  sidebar:
    style: "floating"
    contents:
      - section: "Content"
        contents:
          - index.qmd
          - Lab2.qmd
          - Assignment1.qmd
          - Lab3.qmd
          - Lab4.qmd
          - Assignment2.qmd

  page-footer: 
    left: "Created by Aki Shiroshita"

# Set the language that should be used for Quarto websites
# https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/language
# lang: en

# Set default options for every webpage that may or may not include webR.
webr: 
  show-startup-message: false    # Display status of webR initialization
  show-header-message: false     # Check to see if COOP&COEP headers are set for speed.
  packages: ['ggplot2', 'dplyr'] # Pre-install dependencies
#  base-url: ''                   # Base URL used for specifying where R WebAssembly binaries should be located
#  home-dir: '/home/rstudio'      # Customize where the working directory is
#  channel-type: 'post-message'   # Specify communication channel
#  service-worker-url: ''         # URL from where to load JavaScript worker scripts when loading webR with the ServiceWorker communication channel.

# Attach webR to every page
filters:
  - webr